---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: main-pool
  namespace: metallb
spec:
  addresses:
  - 192.168.43.128/32
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: main
  namespace: metallb
spec:
  ipAddressPools:
  - main-pool  
