{{- if .Values.backend.index.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "haystack.backend.index.fullname" . }}
  labels:
    {{- include "haystack.backend.indexLabels" . | nindent 4 }}
  {{- with .Values.backend.index.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.backend.index.serviceAccount.automount }}
{{- end }}
