{{- if not .Values.global.secrets.useExternalSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "haystack.backend.secrets.fullname" . }}
  labels:
    {{- include "haystack.backend.commonLabels" . | nindent 4 }}
    app.kubernetes.io/instance: commmon-backend-secrets
type: Opaque
data:
  opensearch-user: {{ .Values.global.secrets.opensearch.adminUser | b64enc }}
  opensearch-password: {{ .Values.global.secrets.opensearch.adminPassword | b64enc }}
  openai-api-key: {{ .Values.global.secrets.openai.apiKey | b64enc }}
{{- end }}
